vuejs-translations/docs-cs

.vitepress/config.ts, .vitepress/theme/styles/index.css, vercel.json
resolves #null
Cherry picked from https://github.com/vuejs/docs/commit/d20200ffd1a24c3f36fd3fa102bd6e1aff30a6d6
=> chore: add vercel config for translations 

src/about/team/members-core.json
resolves #23
Cherry picked from https://github.com/vuejs/docs/commit/4f8a885f9bab59ee872999d159c6af526c60c5bf
=> fix: change redirection link (#23)

src/guide/built-ins/transition-demos/NestedTransitions.vue
resolves #34
Cherry picked from https://github.com/vuejs/docs/commit/64d58ad9a14b302b292b669a033328e330f68b13
=> fix: transition nested example (#34)

src/guide/components/props.md
resolves #45
Cherry picked from https://github.com/vuejs/docs/commit/d3e37ab8a967d98debecf7860a91670b7a4a9f8e
=> Update props.md (#2697)

src/guide/components/props.md, src/guide/essentials/reactivity-fundamentals.md, src/guide/essentials/watchers.md
resolves #47
Cherry picked from https://github.com/vuejs/docs/commit/10065c74cbb0b4be7513dd03970daad729e630f5
=> docs: add once option on watcher (#2698)

src/guide/built-ins/transition.md
resolves #50
Cherry picked from https://github.com/vuejs/docs/commit/6505adea5569f00dd4aade876c830b1976578b25
=> docs: add transition + key example (#50)

src/guide/built-ins/transition.md
resolves #58
Cherry picked from https://github.com/vuejs/docs/commit/e72e53ec7541dbea6c7c2c33312aeb46800f16b9
=> docs: add missing comments to the Options API in the transition page (#58)

src/api/compile-time-flags.md
resolves #65
Cherry picked from https://github.com/vuejs/docs/commit/21d4c17faad43a1b294c37063812ab595e66f759
=> Fix "Hydration" typo (#65)

src/ecosystem/newsletters.md
resolves #74
Cherry picked from https://github.com/vuejs/docs/commit/90c792983b2c5106ac9216e9a43568cea06e9830
=> remove inactive newsletter (#74)

.vitepress/config.ts
resolves #78
Cherry picked from https://github.com/vuejs/docs/commit/31d6411b8b41e9e947ef0c91b477e175ba189b6e
=> update discord link in nav (#78)

.gitignore, .idea/.gitignore, .idea/aws.xml, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/docs.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, .vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
resolves #83
Cherry picked from https://github.com/vuejs/docs/commit/0910c205e60d1d929a910a15f2501a7308f2f818
=> add vueconf.us banner (#83)

src/ecosystem/themes/themes.json
resolves #86
Cherry picked from https://github.com/vuejs/docs/commit/6db6990bd7064fc225de87fdbde648fc94d3c0c9
=> Added Wrappixel Templates (#86)

src/guide/components/v-model.md
resolves #95
Cherry picked from https://github.com/vuejs/docs/commit/90ed83113b72291f262c1d1db105cdcea604f94a
=> docs: fix typo - count should be model #2749

.vitepress/theme/index.ts, src/about/team/members-partner.json
resolves #104
Cherry picked from https://github.com/vuejs/docs/commit/6f9e86709ac80fd19e8c95455fe4a582e7791702
=> update vincent avatar url (#104)

src/about/team/members-partner.json
resolves #100
Cherry picked from https://github.com/vuejs/docs/commit/708a6637ba33a8aa461b338a5592dce0aec56547
=> update jos avatar image (#100)

.vitepress/theme/index.ts, src/about/team/members-partner.json
resolves #102
Cherry picked from https://github.com/vuejs/docs/commit/38088c320d1b364d9ce0e9a0e08216c98a721dda
=> disable vueconf banner temporarily (#102)

package.json, pnpm-lock.yaml
resolves #108
Cherry picked from https://github.com/vuejs/docs/commit/d6252cdae0412e397029c983cd9ce9294cd9d32a
=> bump to vitepress 1.0 (#108)

src/guide/essentials/class-and-style.md
resolves #114
Cherry picked from https://github.com/vuejs/docs/commit/d01c5b3b6e117a68fd2d82fb2689590df272ea0f
=> Use the correct class variable based on the context (#114)

.vitepress/config.ts
resolves #120
Cherry picked from https://github.com/vuejs/docs/commit/88a601b3c8cef4581cc19d5878c1a87998e09894
=> adjust translations dropdown order to match completion order (#120)

.vitepress/config.ts, .vitepress/theme/index.ts
resolves #122
Cherry picked from https://github.com/vuejs/docs/commit/66316a0f97d5068f2d9b50ba8cf3b8240309b7e8
=> re-enable vueconf us banner (#122)

src/guide/quick-start.md
resolves #129
Cherry picked from https://github.com/vuejs/docs/commit/53d29c51c886adf8c70cc0f4f164b09754c12656
=> chore: update create-vue output (#129)

src/examples/utils.ts
resolves #136
Cherry picked from https://github.com/vuejs/docs/commit/480e12d00d4d6c7c61c90c2877e68f7a292ca819
=> fix: don't trigger onHashChange if path is not the same (#136)

package.json, pnpm-lock.yaml, src/examples/utils.ts
resolves #138
Cherry picked from https://github.com/vuejs/docs/commit/a17717537cdc9c6e546a62424de88d83dd228f33
=> chore: bump vitepress, revert #2792 (#138)

.vitepress/config.ts
resolves #141
Cherry picked from https://github.com/vuejs/docs/commit/6e1c211f3a0a40314ccfc73f95f683cb885f029f
=> chore: update algolia api key (#141)

src/examples/src/list-transition/App/style.css, src/examples/src/list-transition/App/template.html
resolves #150
Cherry picked from https://github.com/vuejs/docs/commit/4cda22682450f1d3ce35bde4d04c3eea2ddc3a15
=> docs: change tag from div to li element (#150)

.vitepress/theme/index.ts
resolves #152
Cherry picked from https://github.com/vuejs/docs/commit/7da76f683954052ba858c174af387497c8f3e5f3
=> disable banner (#152)

LICENSE
resolves #158
Cherry picked from https://github.com/vuejs/docs/commit/8cf681562260f8624ef062512485fbc86870dec5
=> update license to CC-BY-4.0 and explicitly exclude images (#158)

LICENSE, src/guide/components/v-model.md
resolves #161
Cherry picked from https://github.com/vuejs/docs/commit/21cd803662e9ed58ca0253cd21ebba2acad82ae9
=> docs: format code block comments (#161)

src/api/reactivity-utilities.md
resolves #197
Cherry picked from https://github.com/vuejs/docs/commit/b786ffd8cb02ade7d40622e292fb13c0f5c133cd
=> feat: update isProxy() param type (#197)

.vitepress/headerMdPlugin.ts
resolves #206
Cherry picked from https://github.com/vuejs/docs/commit/35e8da8b3811615e3a46770cf4466186ac9ff400
=> fix: broken header plugin (#206)

.vitepress/headerMdPlugin.ts, src/guide/quick-start.md
resolves #209
Cherry picked from https://github.com/vuejs/docs/commit/678753fed7aa6922ac105da8a06d356bffbdd91f
=> docs: update /guide/quick-start page (#209)

.vitepress/theme/styles/inline-demo.css, src/api/sfc-spec.md
resolves #224
Cherry picked from https://github.com/vuejs/docs/commit/3de891cd0c225b21698503e35f1203f598b970c4
=> style: fix play button alignment (#224)

.vitepress/headerMdPlugin.ts, package.json, pnpm-lock.yaml
resolves #229
Cherry picked from https://github.com/vuejs/docs/commit/4447a5e1b78ff308ed1f426cff21109ad42de412
=> revert: #2878 (#229)

.npmrc
resolves #232
Cherry picked from https://github.com/vuejs/docs/commit/e276daba15586ca2f993661cc0d7fe9ce84954d7
=> chore: add .npmrc (#232)

src/guide/extras/rendering-mechanism.md
resolves #254
Cherry picked from https://github.com/vuejs/docs/commit/a7d0726f7180c6a474bc13050d0ced8fd9cd68b0
=> fix: update example in guide/extras/rendering-mechanism (#254)

src/api/render-function.md
resolves #272
Cherry picked from https://github.com/vuejs/docs/commit/9eaf513ea69b69280a83fd0bc608b80dc4f198ec
=> docs(withModifiers): change type of withModifiers param (#272)

pnpm-lock.yaml, src/api/render-function.md
resolves #275
Cherry picked from https://github.com/vuejs/docs/commit/4787a13e758606bffafc2268a4bf03e413244497
=> chore(deps): bump @vue/repl from 4.2.1 to 4.3.1 (#275)

src/examples/src/fetching-data/App/composition.js, src/examples/src/fetching-data/App/options.js, src/examples/src/fetching-data/App/template.html
resolves #285
Cherry picked from https://github.com/vuejs/docs/commit/327acb65fa9537e78c4e5d677fcfda121935a8f8
=> fix: render error for fetching-data example (#285)

.vitepress/config.ts, package.json
resolves #293
Cherry picked from https://github.com/vuejs/docs/commit/433d4beaac65a0e1dc3e3a77ec261ca5072dc542
=> feat: generate sitemap (#293)

.vitepress/config.ts, .vitepress/theme/components/SponsorsAside.vue, package.json, pnpm-lock.yaml
resolves #298
Cherry picked from https://github.com/vuejs/docs/commit/4d5b2e2f000586785dea7f33a9f7ec7e371a4200
=> chore: correct viteconf CTA utm (#298)

src/guide/quick-start.md, src/guide/scaling-up/tooling.md
resolves #300
Cherry picked from https://github.com/vuejs/docs/commit/4de8ccbd3cec588b10625e1b3109489cafde6abb
=> Update yarn create command (#300)

.vitepress/theme/styles/style-guide.css, pnpm-lock.yaml, src/guide/quick-start.md, src/guide/scaling-up/tooling.md
resolves #304
Cherry picked from https://github.com/vuejs/docs/commit/a66c91698fe1e9314c86ed1729a06d0166c2d485
=> fix: summary add cursor pointer (#304)

src/developers/developers.json
resolves #381
Cherry picked from https://github.com/vuejs/docs/commit/b15177c4bcfe7e37958ff3a19a13dd9d8756cd18
=> docs(developers): remove duplicate text (#381)

src/about/team/members-core.json
resolves #412
Cherry picked from https://github.com/vuejs/docs/commit/929aff014b0595dda64f31361e8b37b5d6eb750c
=> Update Natalia's role (#412)

package.json, pnpm-lock.yaml
resolves #415
Cherry picked from https://github.com/vuejs/docs/commit/f7a57b844f9e6a1715d3593ffc7d459056db005b
=> bump vitepress (#415)

README.md
`potřebje`
`potřebje` -> `potřebuje`
=> README(fix): typo
